### ISSUE TITLE
Issue reading in G140M resolving power table.

### ISSUE THREAD

**Issue by karinsandstrom** [GOALS-survey/CAFE#85]
When I attempt to use the G140M resolution, I get an error "Exception: Resolving power table format not recognized".  Happy to paste the full error message if this is useful.  I am not sure why this doesn't work.  G235M and G395M both work fine and it appears to be the same table, just with different lines commented out.

**Comment by karinsandstrom** [comment]
It is a typo in the table, there is a + sign before the comment on the first line.

**Comment by tdiazsantos** [comment]
Hi Karin,
Sorry it took an awful amount of time to respond, but glad the problem was a typo that you managed to find quickly (we have updated it in the new version). In any case, I hope CAFE is being useful to you.
